#!/bin/sh

#SBATCH --job-name="flow"
#SBATCH --partition=3090_risk
#SBATCH --exclude=aisurrey11
#SBATCH --gpus=4
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --mem=100G
#SBATCH --time=03-00:00:00 
#SBATCH -o slurm_run/slurm.%N.%j.out 
#SBATCH -e slurm_run/slurm.%N.%j.err


# Launch training

accelerate launch --multi_gpu --num_processes 2 train_accelerate.py --config="./configs/speech2speech.yaml"

