---
sample_rate: 22050
clip_duration: 5.

train_datasets:
    INSTRUCTION_SPEECH:
        root: "/mnt/fast/nobackup/scratch4weeks/yc01815/Speech_gen_dataset/gen_speech_v1/train_instruct.csv"
        split: "train"

test_datasets:
    INSTRUCTION_SPEECH:
        root: "/mnt/fast/nobackup/scratch4weeks/yc01815/Speech_gen_dataset/gen_speech_v1/valid_instruct.csv"
        split: "test"

sampler: InfiniteSampler

data_transform: 
    name: Speech2Speech_Mel

save_dir: "/mnt/fast/nobackup/scratch4weeks/yc01815/audio_flow_ata_attn"

model:
    name: BSRoformerMel
    y_dim:  # Leave blank if None
    c_dim: 768 # Leave blank if None
    ct_dim:  # Leave blank if None
    ctf_dim: 
    cx_dim:  # Leave blank if None
    cld_dim: 
    ata: True

    in_channels: 1
    patch_size: [4, 4]
    n_layer: 12
    n_head: 12
    n_embd: 384

train:
    device: cuda
    num_workers: 8
    precision: "no"  # "no" (fp32) | "fp8" | "fp16" | bf16 
    loss: l1
    optimizer: AdamW
    lr: 1e-4
    warm_up_steps: 1000  # Leave blank if no warm up is used
    batch_size_per_device: 2
    test_every_n_steps: 2000
    record_every_n_steps: 100
    save_every_n_steps: 20000
    training_steps: 200000
    resume_ckpt_path:  # Leave blank if train from scratch

valid_audios: 2